/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smarthome.smarthome;
import java.awt.Color;
import smarthome.smarthome.SmartHome;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author L340
 */
public class DashboardJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DashboardJFrame
     */
    Connection conn;
    public String kamar, depan, belakang;
    
    public DashboardJFrame() {
        conn = SmartHome.getConnection();
        initComponents();
        getData();
    }
    
    private void getData(){
        try {
            String sql = "SELECT * FROM tbl_smart_home ORDER BY id DESC LIMIT 1";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            rs.next();
            depan = rs.getString("lampu_depan");
            kamar = rs.getString("lampu_kamar");
            belakang = rs.getString("lampu_belakang");
            System.out.println(depan+" | "+kamar+" | "+belakang);
            
            if (depan.equals("1")) {
                jButtonDepan.setBackground(Color.red);
            } else {
                jButtonDepan.setBackground(Color.GRAY);
            }
            if (kamar.equals("1")) {
                jButtonKamar.setBackground(Color.yellow);
            } else {
                jButtonKamar.setBackground(Color.GRAY);
            }
            if (belakang.equals("1")) {
                jButtonBelakang.setBackground(Color.green);
            } else {
                jButtonBelakang.setBackground(Color.GRAY);
            }
            
            rs.close();
            st.close();
        }catch (Exception e){
             Logger.getLogger(DashboardJFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonKamar = new javax.swing.JButton();
        jButtonDepan = new javax.swing.JButton();
        jButtonBelakang = new javax.swing.JButton();
        jButtonData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frame SMART HOME");

        jButtonKamar.setText("LAMPU KAMAR");

        jButtonDepan.setText("LAMPU DEPAN");
        jButtonDepan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepanActionPerformed(evt);
            }
        });

        jButtonBelakang.setText("LAMPU BELAKANG");
        jButtonBelakang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBelakangActionPerformed(evt);
            }
        });

        jButtonData.setText("Data");
        jButtonData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonData)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDepan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDepan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(jButtonData)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        this.setVisible(false);
        // new MahasiswaJFrame().setVisible(true);
        DataJFrame dataJFrame = new DataJFrame();
        dataJFrame.pack();
        dataJFrame.setLocationRelativeTo(null);
        dataJFrame.setVisible(true);
    }//GEN-LAST:event_jButtonDataActionPerformed

    private void jButtonDepanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepanActionPerformed
        // TODO add your handling code here:
        String messages;
        if (depan.equals("0")) {
            jButtonDepan.setBackground(Color.red);
            depan = "1";
            messages = "Lampu Depan ON";
        } else {
            jButtonDepan.setBackground(Color.GRAY);
            depan = "0";
            messages = "Lampu Depan OFF";
        }
        runLampMySQL(messages);
    }//GEN-LAST:event_jButtonDepanActionPerformed

    private void jButtonKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKamarActionPerformed
        // TODO add your handling code here:
        //jButtonKamar.setBorderPainted(false);
        //jButtonKamar.setOpaque(true);
        String messages;
        if (kamar.equals("0")) {
            jButtonKamar.setBackground(Color.yellow);
            kamar = "1";
            messages = "Lampu Kamar ON";
        } else {
            jButtonKamar.setBackground(Color.GRAY);
            kamar = "0";
            messages = "Lampu Kamar OFF";
        }
        runLampMySQL(messages);
    }//GEN-LAST:event_jButtonDepanActionPerformed

    private void jButtonBelakangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBelakangActionPerformed
        // TODO add your handling code here:
        String messages;
        if (belakang.equals("0")) {
            jButtonBelakang.setBackground(Color.green);
            belakang = "1";
            messages = "Lampu Belakang ON";
        } else {
            jButtonBelakang.setBackground(Color.GRAY);
            belakang = "0";
            messages = "Lampu Belakang OFF";
        }
        runLampMySQL(messages);
    }//GEN-LAST:event_jButtonBelakangActionPerformed
    private void runLampMySQL(String messages){
        try {
            String sql = "INSERT INTO tbl_smart_home VALUES (null,?,?,?,now())";
            PreparedStatement st = conn.prepareStatement(sql);

            st.setString(1, kamar);
            st.setString(2, depan);
            st.setString(3, belakang);

            int rowInserted = st.executeUpdate();
            if (rowInserted > 0) {
                JOptionPane.showMessageDialog(this, messages);
                getData(); 
            } else {
                JOptionPane.showMessageDialog(this, "Gagal Menambahkan Data", "Error", JOptionPane.ERROR_MESSAGE);
            }

            st.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DashboardJFrame boardJFrame = new DashboardJFrame();
                boardJFrame.pack();
                boardJFrame.setLocationRelativeTo(null);
                boardJFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBelakang;
    private javax.swing.JButton jButtonData;
    private javax.swing.JButton jButtonDepan;
    private javax.swing.JButton jButtonKamar;
    // End of variables declaration//GEN-END:variables
}
